version: "3"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  vue-storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run storybook
    volumes:
      - .:/app
    ports:
      - "6006:6006"